[package]
name = "fcsv"
version = "0.1.0"
authors = ["Hideo Hattori <hhatto.jp@gmail.com>"]

[lib]
name = "csv"
crate-type = ["cdylib"]

[dependencies]
csv = "1.0.0"

[dependencies.pyo3]
version = "0.4"
features = ["extension-module"]
